services:
    _defaults:
        autowire: true
        autoconfigure: true

    SymfonySymfonyBundle\UIBundle\Query\:
        resource: '../../../src/*'
        exclude:
            - '../../../src/DependencyInjection/'
