services:
    _defaults:
        autowire: true
        autoconfigure: true

    Bundle\UIBundle\:
        resource: '../../../src/*'
        exclude:
            - '../../../src/DependencyInjection/'

    Bundle\UIBundle\Core\Service\ValidatorService:
        class: Bundle\UIBundle\Core\Service\ValidatorService
        public: true

    Bundle\UIBundle\Core\Dto\Locale:
        arguments: [ '%locale%' ]